import Sidebar from "@/app/components/structure/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Followers from "@/app/components/structure/Followers";
import ToastProvider from "@/provider/ToastProvider";
import { followSuggestions, getUserNotification } from "./actions";
import { Follow, Notification } from "@/types";
import { getCurrentUser } from "./lib/auth";
import AuthPage from "./components/AuthPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Miles-Tweets",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //get currentUser
  const currentUser = await getCurrentUser();

  //get suggested users to follow
  const users = (await followSuggestions()) as Follow[];
  //get user notification
  const notification = (await getUserNotification()) as Notification;

  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider />

        <div className="bg-black">
          {currentUser === null && <AuthPage />}
          <div
            className={`${
              currentUser !== null &&
              "grid grid-cols-4 max-w-7xl mx-auto h-screen"
            }`}
          >
            {currentUser !== null && <Sidebar notification={notification} />}
            <main
              className={`${
                currentUser !== null &&
                "col-span-3 lg:col-span-2 border-x-[1px] border-neutral-800"
              }`}
            >
              {children}
            </main>
            {currentUser !== null && <Followers users={users} />}
          </div>
        </div>
      </body>
    </html>
  );
}
